from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.velocity = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.velocity.setFont(font)
        self.velocity.setText("")
        self.velocity.setObjectName("velocity")
        self.horizontalLayout_14.addWidget(self.velocity)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.angle = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.angle.setFont(font)
        self.angle.setObjectName("angle")
        self.horizontalLayout_15.addWidget(self.angle)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.x_coord = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x_coord.setFont(font)
        self.x_coord.setObjectName("x_coord")
        self.horizontalLayout_16.addWidget(self.x_coord)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.y_coord = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.y_coord.setFont(font)
        self.y_coord.setObjectName("y_coord")
        self.horizontalLayout_17.addWidget(self.y_coord)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.koeff1 = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.koeff1.setFont(font)
        self.koeff1.setObjectName("koeff1")
        self.horizontalLayout_6.addWidget(self.koeff1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.koeff = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.koeff.setFont(font)
        self.koeff.setObjectName("koeff")
        self.horizontalLayout_7.addWidget(self.koeff)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.horizontalLayout_8.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.vx_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vx_3d.setFont(font)
        self.vx_3d.setObjectName("vx_3d")
        self.horizontalLayout_3.addWidget(self.vx_3d)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.x_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x_3d.setFont(font)
        self.x_3d.setObjectName("x_3d")
        self.horizontalLayout_3.addWidget(self.x_3d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.vy_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vy_3d.setFont(font)
        self.vy_3d.setObjectName("vy_3d")
        self.horizontalLayout_4.addWidget(self.vy_3d)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.y_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.y_3d.setFont(font)
        self.y_3d.setObjectName("y_3d")
        self.horizontalLayout_4.addWidget(self.y_3d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.vz_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vz_3d.setFont(font)
        self.vz_3d.setObjectName("vz_3d")
        self.horizontalLayout_5.addWidget(self.vz_3d)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.z_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.z_3d.setFont(font)
        self.z_3d.setObjectName("z_3d")
        self.horizontalLayout_5.addWidget(self.z_3d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.koeff1_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.koeff1_3d.setFont(font)
        self.koeff1_3d.setObjectName("koeff1_3d")
        self.horizontalLayout_9.addWidget(self.koeff1_3d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.koeff_3d = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.koeff_3d.setFont(font)
        self.koeff_3d.setObjectName("koeff_3d")
        self.horizontalLayout_10.addWidget(self.koeff_3d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.widget_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.star_mass = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.star_mass.setFont(font)
        self.star_mass.setObjectName("star_mass")
        self.verticalLayout_6.addWidget(self.star_mass)
        self.star_mass_box = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.star_mass_box.setFont(font)
        self.star_mass_box.setObjectName("star_mass_box")
        self.verticalLayout_6.addWidget(self.star_mass_box)
        self.horizontalLayout_18.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.add_planet = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_planet.setFont(font)
        self.add_planet.setObjectName("add_planet")
        self.horizontalLayout_11.addWidget(self.add_planet)
        self.dis_added = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dis_added.setFont(font)
        self.dis_added.setObjectName("dis_added")
        self.horizontalLayout_11.addWidget(self.dis_added)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_discard = QtWidgets.QAction(MainWindow)
        self.action_discard.setObjectName("action_discard")
        self.action_settings = QtWidgets.QAction(MainWindow)
        self.action_settings.setObjectName("action_settings")
        self.mercury = QtWidgets.QAction(MainWindow)
        self.mercury.setObjectName("mercury")
        self.venus = QtWidgets.QAction(MainWindow)
        self.venus.setObjectName("venus")
        self.earth = QtWidgets.QAction(MainWindow)
        self.earth.setObjectName("earth")
        self.mars = QtWidgets.QAction(MainWindow)
        self.mars.setObjectName("mars")
        self.jupiter = QtWidgets.QAction(MainWindow)
        self.jupiter.setObjectName("jupiter")
        self.saturn = QtWidgets.QAction(MainWindow)
        self.saturn.setObjectName("saturn")
        self.uranus = QtWidgets.QAction(MainWindow)
        self.uranus.setObjectName("uranus")
        self.neptune = QtWidgets.QAction(MainWindow)
        self.neptune.setObjectName("neptune")
        self.pluto = QtWidgets.QAction(MainWindow)
        self.pluto.setObjectName("pluto")
        self.action_added = QtWidgets.QAction(MainWindow)
        self.action_added.setObjectName("action_added")
        self.menu.addAction(self.action_about)
        self.menu_3.addAction(self.mercury)
        self.menu_3.addAction(self.venus)
        self.menu_3.addAction(self.earth)
        self.menu_3.addAction(self.mars)
        self.menu_3.addAction(self.jupiter)
        self.menu_3.addAction(self.saturn)
        self.menu_3.addAction(self.uranus)
        self.menu_3.addAction(self.neptune)
        self.menu_3.addAction(self.pluto)
        self.menu_2.addAction(self.action_discard)
        self.menu_2.addAction(self.action_settings)
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menu_2.addAction(self.action_added)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Небесная механика"))
        self.label_11.setText(_translate("MainWindow", "Скорость:"))
        self.label_12.setText(_translate("MainWindow", "Угол к оси x:"))
        self.label_13.setText(_translate("MainWindow", "x:"))
        self.label_14.setText(_translate("MainWindow", "y:"))
        self.label_7.setText(_translate("MainWindow", "Коэф. сопротивления среды:"))
        self.label_8.setText(_translate("MainWindow", "Коэф. силы тяги:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "2D"))
        self.label.setText(_translate("MainWindow", "Скорость на ось x:"))
        self.label_4.setText(_translate("MainWindow", "x:"))
        self.label_2.setText(_translate("MainWindow", "Скорость на ось y:"))
        self.label_5.setText(_translate("MainWindow", "y:"))
        self.label_3.setText(_translate("MainWindow", "Скорость на ось z:"))
        self.label_6.setText(_translate("MainWindow", "z:"))
        self.label_9.setText(_translate("MainWindow", "Коэф. сопротивления среды:"))
        self.label_10.setText(_translate("MainWindow", "Коэф. силы тяги:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "3D"))
        self.label_15.setText(_translate("MainWindow", "Масса звезды:"))
        self.pushButton.setText(_translate("MainWindow", "Построить"))
        self.add_planet.setText(_translate("MainWindow", "Добавить"))
        self.dis_added.setText(_translate("MainWindow", "Сбросить добавленное"))
        self.menu.setTitle(_translate("MainWindow", "Помощь"))
        self.menu_2.setTitle(_translate("MainWindow", "Инструменты"))
        self.menu_3.setTitle(_translate("MainWindow", "Солнечная система"))
        self.action_about.setText(_translate("MainWindow", "О программе"))
        self.action_discard.setText(_translate("MainWindow", "Сбросить"))
        self.action_settings.setText(_translate("MainWindow", "Настройки"))
        self.mercury.setText(_translate("MainWindow", "Меркурий"))
        self.venus.setText(_translate("MainWindow", "Венера"))
        self.earth.setText(_translate("MainWindow", "Земля"))
        self.mars.setText(_translate("MainWindow", "Марс"))
        self.jupiter.setText(_translate("MainWindow", "Юпитер"))
        self.saturn.setText(_translate("MainWindow", "Сатурн"))
        self.uranus.setText(_translate("MainWindow", "Уран"))
        self.neptune.setText(_translate("MainWindow", "Нептун"))
        self.pluto.setText(_translate("MainWindow", "Плутон"))
        self.action_added.setText(_translate("MainWindow", "Добавленные значения"))
